familyBackground:
  - "Raised in an American family with healthcare professionals. Parents work in medicine, inspiring early interest in helping others."
  - "Coming from a household that values both scientific achievement and compassionate patient care."
  - "Grew up in a supportive family that encouraged academic excellence and community service."

interests:
  - "Passionate about medical research and follows developments in biotechnology and pharmaceutical sciences."
  - "Interested in healthcare accessibility and public health policy in the United States."
  - "Volunteers at local healthcare facilities and participates in medical outreach programs."

academicGoals:
  - "Aims to become a physician contributing to American healthcare system advancement."
  - "Plans to specialize in a medical field that combines clinical practice with research."
  - "Goal is to develop expertise in patient care while contributing to medical knowledge."
