familyBackground:
  - "Raised in a Polish family with medical traditions. Parents work in healthcare, instilling respect for the profession from early age."
  - "Coming from a traditional Polish household in Lublin where community service and helping others are core values."
  - "Grew up in a supportive Polish family that encouraged empathy and scientific curiosity. Regular discussions about health and wellbeing."

interests:
  - "Passionate about medical research and follows developments in Polish healthcare system closely. Volunteers at local clinics."
  - "Interested in preventive medicine and public health initiatives. Participates in health awareness campaigns."
  - "Enjoys learning about medical innovations and their practical applications in patient care."

academicGoals:
  - "Aims to become a physician contributing to Poland's healthcare system while advancing medical knowledge."
  - "Plans to specialize in internal medicine and eventually work in clinical research."
  - "Goal is to combine patient care with medical education to train future healthcare professionals in Poland."
