familyBackground:
  - "Raised in a family with engineering traditions in China's industrial heartland. Parents work in manufacturing sector."
  - "Coming from a household in Shenzhen where technological innovation and engineering excellence are highly valued."
  - "Grew up in a family that encouraged hands-on technical projects. Early exposure to China's rapid infrastructure development."

interests:
  - "Passionate about high-speed rail technology and modern infrastructure systems. Follows China's engineering achievements closely."
  - "Interested in green technology and sustainable engineering solutions for urban development."
  - "Enjoys building electronics projects and participating in engineering design competitions."

academicGoals:
  - "Aims to contribute to China's continued infrastructure development through advanced engineering skills."
  - "Plans to specialize in renewable energy engineering and sustainable construction methods."
  - "Goal is to develop expertise in smart city technologies and urban engineering systems."
