familyBackground:
  - "Raised in a German family with business traditions. Parents run a Mittelstand company with strong regional roots."
  - "Coming from a household in Hamburg with connections to international trade and commerce."
  - "Grew up in a family in Dusseldorf that values both traditional business practices and modern management approaches."

interests:
  - "Passionate about German Mittelstand model and how medium-sized businesses drive economic success."
  - "Interested in sustainable business practices and corporate governance in European markets."
  - "Follows EU business regulations and their impact on corporate strategy."

academicGoals:
  - "Aims to develop comprehensive business skills to contribute to Germany's economic landscape."
  - "Plans to specialize in operations management or supply chain optimization."
  - "Goal is to gain expertise in business administration and eventually lead a family or established company."
