familyBackground:
  - "Raised in a traditional Polish family in Krakow, where academic achievement is highly valued. Parents, both engineers, instilled a strong work ethic."
  - "Coming from a middle-class Polish household in Warsaw. Family gatherings often involve discussions about technology and education."
  - "Grew up in Gdansk in a supportive Polish family that encouraged exploration of science and mathematics from an early age."

interests:
  - "Passionate about competitive programming and participates in local coding competitions. Enjoys building open-source tools in free time."
  - "Interested in cybersecurity and spends weekends exploring CTF challenges. Also enjoys chess and strategy games."
  - "Fascinated by machine learning applications. Runs a small tech blog discussing AI developments in Polish."

academicGoals:
  - "Aims to specialize in distributed systems and contribute to Poland's growing tech sector after graduation."
  - "Plans to pursue research in artificial intelligence while building practical industry experience through internships."
  - "Goal is to develop expertise in software architecture and eventually lead technical teams at major tech companies."
