familyBackground:
  - "Raised in a German family in Munich that values technical precision and academic excellence. Parents work in engineering fields."
  - "Coming from a household in Berlin where Bildung (education) is seen as essential for personal and professional development."
  - "Grew up in Frankfurt in a family that encouraged systematic thinking and rigorous academic preparation."

interests:
  - "Passionate about software engineering best practices and follows German tech industry developments closely."
  - "Interested in enterprise software development and contributes to open-source projects."
  - "Enjoys participating in coding competitions and learning new programming paradigms."

academicGoals:
  - "Aims to develop strong technical foundations and contribute to Germany's growing software industry."
  - "Plans to specialize in systems programming or embedded software development."
  - "Goal is to gain comprehensive computer science knowledge and work for major German tech companies."
