familyBackground:
  - "Raised in an industrial Polish city where engineering traditions run deep. Father works in manufacturing, inspiring early interest in how things work."
  - "Coming from a Polish family in Silesia with strong connections to heavy industry. Grandparents worked in mining and steel production."
  - "Grew up in Wroclaw in a family that values practical skills. Parents encouraged hands-on projects and technical problem-solving."

interests:
  - "Passionate about renewable energy systems and their implementation in Poland. Participates in engineering design competitions."
  - "Interested in automotive engineering and follows developments in electric vehicle technology closely."
  - "Enjoys building mechanical projects and has completed several robotics kits. Active in local maker communities."

academicGoals:
  - "Aims to contribute to Poland's industrial modernization through innovative engineering solutions."
  - "Plans to specialize in sustainable manufacturing processes and environmental engineering."
  - "Goal is to develop expertise in infrastructure engineering and work on major Polish development projects."
