familyBackground:
  - "Raised in an entrepreneurial Chinese family with a business background. Parents run a successful trading company and value commercial acumen."
  - "Coming from a family in Guangzhou with long traditions in commerce. Business discussions are common at family gatherings."
  - "Grew up in a household where economic awareness and financial literacy were taught from an early age."

interests:
  - "Passionate about e-commerce and digital marketing trends in Chinese markets. Studies successful business models closely."
  - "Interested in sustainable business practices and corporate social responsibility in Asian contexts."
  - "Enjoys analyzing investment opportunities and has participated in stock market simulation competitions."

academicGoals:
  - "Aims to develop comprehensive business skills to contribute to China's evolving commercial landscape."
  - "Plans to specialize in international trade and finance with focus on Asian markets."
  - "Goal is to gain expertise in business strategy and eventually lead significant commercial ventures."
