familyBackground:
  - "Raised in a family in Detroit with automotive industry background. Engineering excellence is a family tradition."
  - "Coming from a household in Houston with connections to aerospace and energy sectors."
  - "Grew up in a practical American family that valued hands-on skills and problem-solving abilities."

interests:
  - "Passionate about aerospace engineering and follows NASA and SpaceX developments closely."
  - "Interested in renewable energy technology and sustainable engineering solutions."
  - "Enjoys building mechanical and electronic projects. Active in local maker spaces and engineering clubs."

academicGoals:
  - "Aims to contribute to American innovation in aerospace or automotive engineering."
  - "Plans to specialize in sustainable energy systems and infrastructure development."
  - "Goal is to develop practical engineering skills and work on impactful technological projects."
