familyBackground:
  - "Raised in an American family in Silicon Valley where technology and innovation are part of daily life. Parents work in tech industry."
  - "Coming from a middle-class household in Texas that values both practical skills and higher education."
  - "Grew up in a supportive family in Boston that encouraged curiosity and academic exploration from an early age."

interests:
  - "Passionate about startup culture and has participated in multiple hackathons. Follows tech industry trends closely."
  - "Interested in open-source software development and contributes to popular GitHub projects."
  - "Enjoys building side projects and experimenting with new programming languages and frameworks."

academicGoals:
  - "Aims to develop expertise in software engineering and eventually join or found a tech startup."
  - "Plans to specialize in machine learning and artificial intelligence applications."
  - "Goal is to build practical technical skills and gain industry experience through internships."
