familyBackground:
  - "Raised in a Chinese family with deep respect for medical professionals. Parents encouraged both academic excellence and compassion."
  - "Coming from a household where traditional Chinese medicine coexists with modern medical practices."
  - "Grew up in a supportive family that values both scientific rigor and humanistic care in healthcare."

interests:
  - "Passionate about integrating traditional and modern medical approaches. Studies both TCM and Western medicine concepts."
  - "Interested in public health initiatives and healthcare accessibility in developing regions."
  - "Enjoys medical research and follows developments in biotechnology and pharmaceutical sciences."

academicGoals:
  - "Aims to become a physician who can contribute to China's healthcare system modernization."
  - "Plans to specialize in internal medicine while maintaining interest in preventive healthcare."
  - "Goal is to combine clinical practice with medical research to advance treatment methods."
